### ISSUE TITLE
Change all of the objects.get() to get_object_404

### ISSUE THREAD

**Issue by vector67** [teampinocchio/pinocchio#42]
According to this answer, we should change all of the object access methods to give a better error message if they come across a nonexistent object.

(http://stackoverflow.com/questions/17813919/django-error-matching-query-does-not-exist#17815743)

**Comment by Jason-vh** [comment]
I'm not sure replacing _every_ instance of get() with [get_object_404()](https://docs.djangoproject.com/en/1.9/topics/http/shortcuts/#get-object-or-404) is the best way to go about this.
It would be a bit puzzling for a user to get a 404 error because for some reason a question in their questionnaire is for some reason not in the database.
I think a better solution would be to use the standard get() and then either handle the [Object.DoesNotExist ](https://docs.djangoproject.com/en/1.9/ref/models/instances/#django.db.models.Model.DoesNotExist) exception or to use the [get_or_create()](https://docs.djangoproject.com/en/dev/ref/models/querysets/#get-or-create) shortcut, depending on the situation.
