### ISSUE TITLE
Account Details for other users doesn't work

### ISSUE THREAD

**Issue by Jason-vh** [teampinocchio/pinocchio#89]
Probably because the url expects a numeric number.

**Comment by Jason-vh** [comment]
I just finished fixing this, and was about to upload it 😂

**Comment by devosray** [comment]
While it _does_ work, it exposes a vulnerability. Since any user can edit the URL, it is possible for students to grap personal info of other students simply by changing the URL. 
For example, http://localhost:8000/accountDetails/admin shows personal information about the admin user, while I'm logged in as a normal user.

**Comment by nigelmpofu** [comment]
I don't think it's an issue because users decide what information they want to share and if someone is not in your team you would still need to know their user id to access their info
